version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    restart: unless-stopped
